name: deploy

on: push

# It is important to specify "concurrency" for the workflow,
# to prevent concurrency between different deploys.
concurrency: production_environment

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Composer install
        run: composer install --no-dev --no-ansi --no-interaction --no-progress --optimize-autoloader

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "./"
          REMOTE_HOST: viking.uber.space
          REMOTE_USER: viking
          TARGET: /home/viking/html/elke-sommer.de
          EXCLUDE: ".env, .github, .git, .ddev, node_modules, storage, public/storage .env, DOCKER_ENV, output.log, Dockerfile-php-build, docker_tag"
          SCRIPT_AFTER: |
            cd /home/viking/html/elke-sommer.de
            php artisan optimize:clear
            php artisan view:cache
            php artisan config:cache
            php artisan route:cache
            php artisan event:cache
            php artisan migrate --force
            php artisan responsecache:clear
